name: sample_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.1
  # riverpod_annotation: ^2.1.6
  http: ^1.2.1
  go_router: ^13.1.0
  hooks_riverpod: ^2.4.5
  # macros: any
  json: ^0.20.1
  flutter_hooks: ^0.20.5
  freezed: ^3.0.0-0.0.dev

# dependency_overrides:
#   macros:
#     git:
#       url: https://github.com/dart-lang/sdk.git
#       path: pkg/macros
#       ref: main
#   _fe_analyzer_shared:
#     git:
#       url: https://github.com/dart-lang/sdk.git
#       path: pkg/_fe_analyzer_shared
#       ref: main

analyzer:
  enable-experiment:
    - macros

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  go_router_builder: ^2.3.4
  # _fe_analyzer_shared: any

flutter:
  uses-material-design: true
