name: sample_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-0.0-dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.1.0
  go_router: ^12.0.1
  hooks_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  dataclass: ^1.0.0
  freezed: ^3.0.0-0.0.dev
  table_calendar: ^3.1.2
  image: ^4.3.0
  image_picker: ^1.1.2
  build_runner: ^2.4.13
  image_picker_web: ^4.0.0
  photo_view: ^0.15.0
  async_queue: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.3
  go_router_builder: ^2.3.4
  # freezed: ^2.4.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Italic-VariableFont_wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-VariableFont_wdth,wght.ttf
          weight: 500

    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy/SourGummy-Italic-VariableFont_wdth,wght.ttf
          weight: 400
        - asset: assets/fonts/SourGummy/SourGummy-VariableFont_wdth,wght.ttf
          weight: 500

    - family: ZenMaruGothic
      fonts:
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenMaruGothic/ZenMaruGothic-Black.ttf
          weight: 900
