name: sample_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.1
  riverpod_annotation: ^2.1.6
  http: ^1.1.0
  go_router: ^12.0.1
  hooks_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  flutter_hooks: ^0.20.5
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  go_router_builder: ^2.3.4
  freezed: ^2.4.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
