name: flutter_hooks_graph_tool
issueTracker: https://github.com/flutter-hooks-graph/flutter-hooks-graph/issues
version: 0.0.1
materialIconCodePoint: '0xe0b1'
requiresConnection: true  # optional field - defaults to true